import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import 'jspdf-autotable'; // ensures doc.autoTable also gets registered on older plugin versions
import { Capacitor } from '@capacitor/core';
import { Filesystem, Directory } from '@capacitor/filesystem';
import { Share } from '@capacitor/share';
import { getCategoryGroup } from '../lib/categories';

// ---------- Brand colors (matches Hisaab's dark/green theme) ----------
const BRAND_GREEN = [16, 185, 129];      // #10b981 - primary brand green
const BRAND_GREEN_DARK = [6, 95, 70];    // darker green for headers
const TEXT_DARK = [30, 41, 59];          // slate-800
const TEXT_MUTED = [100, 116, 139];      // slate-500
const DANGER_RED = [239, 68, 68];
const INFO_BLUE = [59, 130, 246];
const LIGHT_BG = [240, 253, 249];        // very light green tint for zebra rows

// ---------- Native (Android/iOS) save + share helpers ----------
// Directory.Cache needs NO runtime storage permission on Android/iOS.
// Since we immediately hand the file to Share.share() (we're not asking
// the user to keep it long-term ourselves), Cache is the correct,
// permission-free choice.
// (Directory.Documents/External require scoped-storage permissions on
// Android 10+ and throw at writeFile() time if not granted — that was
// the root cause of "Unable to save report natively".)
const savePdfNative = async (pdfBase64, fileName) => {
  const result = await Filesystem.writeFile({
    path: fileName,
    data: pdfBase64,
    directory: Directory.Cache,
    recursive: true,
  });
  return result.uri;
};

const sharePdfNative = async (fileName, uri) => {
  await Share.share({
    title: 'Hisaab Report',
    text: 'Here is your Hisaab financial report.',
    url: uri,
    dialogTitle: 'Share Hisaab Report',
  });
};

const getBase64FromDataUri = (dataUri) => {
  const prefix = 'data:application/pdf;base64,';
  if (dataUri.startsWith(prefix)) {
    return dataUri.substring(prefix.length);
  }
  return dataUri;
};

// ---------- Small drawing helpers ----------
function drawSectionHeading(doc, text, y) {
  doc.setFillColor(...BRAND_GREEN);
  doc.rect(14, y - 5, 3, 7, 'F'); // small accent bar
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(...TEXT_DARK);
  doc.text(text, 20, y);
  doc.setFont('helvetica', 'normal');
  return y + 4;
}

function addFooter(doc) {
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const pageHeight = doc.internal.pageSize.getHeight();
    const pageWidth = doc.internal.pageSize.getWidth();
    doc.setDrawColor(220, 220, 220);
    doc.line(14, pageHeight - 15, pageWidth - 14, pageHeight - 15);
    doc.setFontSize(8);
    doc.setTextColor(...TEXT_MUTED);
    doc.text('Generated by Hisaab \u2022 hisaab0.netlify.app', 14, pageHeight - 9);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 14, pageHeight - 9, { align: 'right' });
  }
}

function checkPageBreak(doc, currentY, neededSpace = 30) {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (currentY + neededSpace > pageHeight - 20) {
    doc.addPage();
    return 25;
  }
  return currentY;
}

// ---------- Main report generator ----------
// summary = {
//   period, transactions: [], emis: [], savingsGoals: [], userEmail
// }
export const generateReport = async (summary) => {
  const {
    period = 'This Month',
    transactions = [],
    emis = [],
    savingsGoals = [],
    userEmail = '',
  } = summary;

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // ================= HEADER / BRANDING =================
  doc.setFillColor(...BRAND_GREEN_DARK);
  doc.rect(0, 0, pageWidth, 32, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text('Hisaab', 14, 18);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(220, 245, 235);
  doc.text('Personal Finance Report', 14, 25);

  doc.setFontSize(9);
  doc.text(`Period: ${period}`, pageWidth - 14, 15, { align: 'right' });
  const genDate = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
  doc.text(`Generated: ${genDate}`, pageWidth - 14, 21, { align: 'right' });
  if (userEmail) {
    doc.text(userEmail, pageWidth - 14, 27, { align: 'right' });
  }

  let y = 44;

  // ================= FINANCIAL SUMMARY =================
  const totalIncome = transactions.filter(t => t.type === 'income').reduce((s, t) => s + Number(t.amount), 0);
  const totalExpense = transactions.filter(t => t.type === 'expense').reduce((s, t) => s + Number(t.amount), 0);
  const netBalance = totalIncome - totalExpense;

  const monthlyEmiCommitment = emis.reduce((s, e) => s + Number(e.monthly_installment), 0);
  const remainingLiability = emis.reduce((s, e) => {
    const remaining = Math.max(0, e.total_installments - e.installments_paid);
    return s + remaining * Number(e.monthly_installment);
  }, 0);

  const totalSavedAcrossGoals = savingsGoals.reduce((s, g) => s + Number(g.current_saved), 0);

  y = drawSectionHeading(doc, 'Financial Summary', y);
  y += 6;

  autoTable(doc, {
    startY: y,
    theme: 'grid',
    styles: { fontSize: 9, cellPadding: 4 },
    headStyles: { fillColor: BRAND_GREEN, textColor: 255, fontStyle: 'bold' },
    columnStyles: { 0: { fontStyle: 'bold' } },
    body: [
      ['Total Income', `Rs. ${totalIncome.toLocaleString('en-IN')}`],
      ['Total Expenses', `Rs. ${totalExpense.toLocaleString('en-IN')}`],
      ['Net Balance', `Rs. ${netBalance.toLocaleString('en-IN')}`],
      ['Monthly EMI Commitment', `Rs. ${monthlyEmiCommitment.toLocaleString('en-IN')}`],
      ['Total Savings (across goals)', `Rs. ${totalSavedAcrossGoals.toLocaleString('en-IN')}`],
    ],
    margin: { left: 14, right: 14 },
  });

  y = doc.lastAutoTable.finalY + 14;

  // ================= 50/30/20 BUDGET BREAKDOWN =================
  // Mirrors BudgetPlanner.jsx logic exactly, using getCategoryGroup from lib/categories
  y = checkPageBreak(doc, y, 60);
  y = drawSectionHeading(doc, '50/30/20 Budget Breakdown', y);
  y += 6;

  const expensesOnly = transactions.filter(t => t.type === 'expense');
  const needsSpent = expensesOnly.filter(t => getCategoryGroup(t.category) === 'Need').reduce((s, t) => s + Number(t.amount), 0);
  const wantsSpent = expensesOnly.filter(t => getCategoryGroup(t.category) === 'Want').reduce((s, t) => s + Number(t.amount), 0);
  const saved = totalIncome - (needsSpent + wantsSpent);
  const pct = (amount) => (totalIncome > 0 ? Math.round((amount / totalIncome) * 100) : 0);

  const needsTarget = totalIncome * 0.5;
  const wantsTarget = totalIncome * 0.3;
  const savingsTarget = totalIncome * 0.2;

  autoTable(doc, {
    startY: y,
    theme: 'grid',
    styles: { fontSize: 9, cellPadding: 4 },
    headStyles: { fillColor: BRAND_GREEN, textColor: 255, fontStyle: 'bold' },
    head: [['Category', 'Target Allocation', 'Actual Spent', '% of Income', 'Status']],
    body: [
      [
        'Needs (50%)',
        `Rs. ${needsTarget.toLocaleString('en-IN')}`,
        `Rs. ${needsSpent.toLocaleString('en-IN')}`,
        `${pct(needsSpent)}%`,
        needsSpent <= needsTarget ? 'Safe Zone' : 'Over Budget',
      ],
      [
        'Wants (30%)',
        `Rs. ${wantsTarget.toLocaleString('en-IN')}`,
        `Rs. ${wantsSpent.toLocaleString('en-IN')}`,
        `${pct(wantsSpent)}%`,
        wantsSpent <= wantsTarget ? 'Safe Zone' : 'Over Budget',
      ],
      [
        'Savings (20%)',
        `Rs. ${savingsTarget.toLocaleString('en-IN')}`,
        `Rs. ${(saved > 0 ? saved : 0).toLocaleString('en-IN')}`,
        `${pct(saved > 0 ? saved : 0)}%`,
        saved >= savingsTarget ? 'Safe Zone' : 'Over Budget',
      ],
    ],
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 4) {
        const val = data.cell.raw;
        data.cell.styles.textColor = val === 'Safe Zone' ? BRAND_GREEN_DARK : DANGER_RED;
        data.cell.styles.fontStyle = 'bold';
      }
    },
    margin: { left: 14, right: 14 },
  });

  y = doc.lastAutoTable.finalY + 14;

  // ================= TRANSACTIONS =================
  y = checkPageBreak(doc, y, 40);
  y = drawSectionHeading(doc, `Recent Transactions (${transactions.length})`, y);
  y += 6;

  if (transactions.length === 0) {
    doc.setFontSize(9);
    doc.setTextColor(...TEXT_MUTED);
    doc.text('No transactions recorded for this period.', 14, y);
    y += 10;
  } else {
    autoTable(doc, {
      startY: y,
      theme: 'striped',
      styles: { fontSize: 8.5, cellPadding: 3 },
      headStyles: { fillColor: BRAND_GREEN, textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: LIGHT_BG },
      head: [['Date', 'Category', 'Note', 'Type', 'Amount']],
      body: transactions
        .slice()
        .sort((a, b) => new Date(b.date) - new Date(a.date))
        .map(t => [
          t.date,
          t.category,
          t.note || '-',
          t.type === 'income' ? 'Income' : 'Expense',
          `${t.type === 'income' ? '+' : '-'}Rs. ${Number(t.amount).toLocaleString('en-IN')}`,
        ]),
      didParseCell: (data) => {
        if (data.section === 'body' && data.column.index === 4) {
          const isIncome = data.row.raw[3] === 'Income';
          data.cell.styles.textColor = isIncome ? BRAND_GREEN_DARK : DANGER_RED;
          data.cell.styles.fontStyle = 'bold';
        }
      },
      margin: { left: 14, right: 14 },
    });
    y = doc.lastAutoTable.finalY + 14;
  }

  // ================= EMI MANAGER =================
  y = checkPageBreak(doc, y, 40);
  y = drawSectionHeading(doc, `EMI / Loan Portfolio (${emis.length})`, y);
  y += 6;

  if (emis.length === 0) {
    doc.setFontSize(9);
    doc.setTextColor(...TEXT_MUTED);
    doc.text('No active EMIs or loans.', 14, y);
    y += 10;
  } else {
    autoTable(doc, {
      startY: y,
      theme: 'striped',
      styles: { fontSize: 8.5, cellPadding: 3 },
      headStyles: { fillColor: [124, 58, 237], textColor: 255, fontStyle: 'bold' }, // purple, matches EMI module
      alternateRowStyles: { fillColor: [245, 243, 255] },
      head: [['Loan', 'Lender', 'Type', 'Monthly EMI', 'Due Day', 'Left', 'Balance']],
      body: emis.map(e => {
        const remaining = Math.max(0, e.total_installments - e.installments_paid);
        const balance = remaining * Number(e.monthly_installment);
        return [
          e.loan_name,
          e.lender || '-',
          e.loan_type,
          `Rs. ${Number(e.monthly_installment).toLocaleString('en-IN')}`,
          `Day ${e.due_day}`,
          `${remaining} mo`,
          `Rs. ${balance.toLocaleString('en-IN')}`,
        ];
      }),
      margin: { left: 14, right: 14 },
    });
    y = doc.lastAutoTable.finalY + 8;

    doc.setFontSize(9);
    doc.setTextColor(...TEXT_DARK);
    doc.setFont('helvetica', 'bold');
    doc.text(`Total Monthly Commitment: Rs. ${monthlyEmiCommitment.toLocaleString('en-IN')}   |   Total Remaining Liability: Rs. ${remainingLiability.toLocaleString('en-IN')}`, 14, y);
    doc.setFont('helvetica', 'normal');
    y += 14;
  }

  // ================= SAVINGS GOALS =================
  y = checkPageBreak(doc, y, 40);
  y = drawSectionHeading(doc, `Savings & Wealth Goals (${savingsGoals.length})`, y);
  y += 6;

  if (savingsGoals.length === 0) {
    doc.setFontSize(9);
    doc.setTextColor(...TEXT_MUTED);
    doc.text('No savings goals created yet.', 14, y);
    y += 10;
  } else {
    autoTable(doc, {
      startY: y,
      theme: 'striped',
      styles: { fontSize: 8.5, cellPadding: 3 },
      headStyles: { fillColor: INFO_BLUE, textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [239, 246, 255] },
      head: [['Goal', 'Target Date', 'Current', 'Target', 'Progress']],
      body: savingsGoals.map(g => {
        const p = g.target_amount > 0 ? Math.min(Math.round((g.current_saved / g.target_amount) * 100), 100) : 0;
        return [
          g.goal_name,
          g.target_date || '-',
          `Rs. ${Number(g.current_saved).toLocaleString('en-IN')}`,
          `Rs. ${Number(g.target_amount).toLocaleString('en-IN')}`,
          `${p}%`,
        ];
      }),
      margin: { left: 14, right: 14 },
    });
    y = doc.lastAutoTable.finalY + 14;
  }

  // ================= FOOTER (all pages) =================
  addFooter(doc);

  // ================= SAVE / SHARE =================
  const fileName = `Hisaab-Report-${new Date().toISOString().slice(0, 10)}.pdf`;

  if (Capacitor.isNativePlatform()) {
    try {
      const dataUri = doc.output('datauristring');
      const base64 = getBase64FromDataUri(dataUri);
      const fileUri = await savePdfNative(base64, fileName);
      await sharePdfNative(fileName, fileUri);
    } catch (error) {
      console.error('Native PDF save failed', error);
      alert('Unable to save report natively. Please try again.');
    }
  } else {
    doc.save(fileName);
  }
};
